/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.PessoaDAO;
import DTO.FuncionarioDTO;
import DTO.PessoaDTO;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thiago
 */
public class frmPessoaVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmPessoaVIEW
     */
    public frmPessoaVIEW() {
        initComponents();
        ListarPessoas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNomePessoa = new javax.swing.JLabel();
        txtNomePessoa = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblIdPessoa = new javax.swing.JLabel();
        txtIdPessoa = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPessoa = new javax.swing.JTable();
        btnCarregarDados = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomePessoa.setText("Nome Pessoa");

        lblCpf.setText("CPF");

        lblIdPessoa.setText("Id Pessoa");

        txtIdPessoa.setEditable(false);
        txtIdPessoa.setEnabled(false);
        txtIdPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPessoaActionPerformed(evt);
            }
        });

        lblDataNascimento.setText("Data Nascimento");

        lblSexo.setText("Sexo");

        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });

        lblEmail.setText("E-mail");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblTelefone.setText("Telefone");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        tblPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PESSOA", "CPF", "NOME", "DATA NASCIMENTO", "SEXO", "EMAIL", "TELEFONE"
            }
        ));
        jScrollPane2.setViewportView(tblPessoa);

        btnCarregarDados.setText("Carregar");
        btnCarregarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNomePessoa)
                            .addComponent(txtNomePessoa)
                            .addComponent(lblCpf)
                            .addComponent(txtCpf)
                            .addComponent(lblIdPessoa)
                            .addComponent(txtIdPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(lblDataNascimento)
                            .addComponent(txtDataNascimento))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSexo)
                            .addComponent(txtSexo)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail)
                            .addComponent(lblTelefone)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addGap(0, 252, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCarregarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPessoa)
                    .addComponent(lblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePessoa)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(lblTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnDeletar)
                    .addComponent(btnCarregarDados))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPessoaActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        CadastrarPessoa();
        LimparCampos();
        ListarPessoas();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        AtualizarPessoa();
        LimparCampos();
        ListarPessoas();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        DeletarPessoa();
        LimparCampos();
        ListarPessoas();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnCarregarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarDadosActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btnCarregarDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPessoaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPessoaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPessoaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPessoaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPessoaVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCarregarDados;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIdPessoa;
    private javax.swing.JLabel lblNomePessoa;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTable tblPessoa;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdPessoa;
    private javax.swing.JTextField txtNomePessoa;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void ListarPessoas() {
        try {
            PessoaDAO objPessoaDAO = new PessoaDAO();
            DefaultTableModel model = (DefaultTableModel) this.tblPessoa.getModel();
            model.setNumRows(0);
            ArrayList<PessoaDTO> lista = objPessoaDAO.PesquisarPessoa();

            for (int num = 0; num < lista.size(); ++num) {
                model.addRow(new Object[]{ 
                    ((PessoaDTO) lista.get(num)).getId_pessoa(), 
                    ((PessoaDTO) lista.get(num)).getCpf(), 
                    ((PessoaDTO) lista.get(num)).getNome(), 
                    ((PessoaDTO) lista.get(num)).getData_nascimento(), 
                    ((PessoaDTO) lista.get(num)).getSexo(), 
                    ((PessoaDTO) lista.get(num)).getEmail(), 
                    ((PessoaDTO) lista.get(num)).getTelefone()
                });
            }
        } catch (Exception var5) {
            JOptionPane.showMessageDialog((Component) null, "Listar Valores VIEW: " + var5);
        }

    }
    
    private void CadastrarPessoa() {
        int cpf = Integer.parseInt(this.txtCpf.getText());
        String nome_pessoa = this.txtNomePessoa.getText();
        String data_nascimento = this.txtDataNascimento.getText();
        String sexo = this.txtSexo.getText();
        String email = this.txtEmail.getText();
        int telefone = Integer.parseInt(this.txtTelefone.getText());
        
        PessoaDTO objPessoaDTO = new PessoaDTO();
        objPessoaDTO.setCpf(cpf);
        objPessoaDTO.setNome(nome_pessoa);
        objPessoaDTO.setData_nascimento(data_nascimento);
        objPessoaDTO.setSexo(sexo);
        objPessoaDTO.setEmail(email);
        objPessoaDTO.setTelefone(telefone);
        PessoaDAO objPessoaDAO = new PessoaDAO();
        objPessoaDAO.cadastrarPessoa(objPessoaDTO);
     
    }
    
    private void AtualizarPessoa() {
        int id_pessoa = Integer.parseInt(this.txtIdPessoa.getText());
        int cpf = Integer.parseInt(this.txtCpf.getText());
        String nome_pessoa = this.txtNomePessoa.getText();
        String data_nascimento = this.txtDataNascimento.getText();
        String sexo = this.txtSexo.getText();
        String email = this.txtEmail.getText();
        int telefone = Integer.parseInt(this.txtTelefone.getText());
        
        PessoaDTO objPessoaDTO = new PessoaDTO();
        objPessoaDTO.setId_pessoa(id_pessoa);
        objPessoaDTO.setCpf(cpf);
        objPessoaDTO.setNome(nome_pessoa);
        objPessoaDTO.setData_nascimento(data_nascimento);
        objPessoaDTO.setSexo(sexo);
        objPessoaDTO.setEmail(email);
        objPessoaDTO.setTelefone(telefone);
        
        PessoaDAO objPessoaDAO = new PessoaDAO();
        objPessoaDAO.alterarPessoa(objPessoaDTO);
    }
    
    private void DeletarPessoa() {
        int cpf = Integer.parseInt(this.txtCpf.getText());
        PessoaDTO objPessoaDTO = new PessoaDTO();
        objPessoaDTO.setCpf(cpf);
        PessoaDAO objPessoaDAO = new PessoaDAO();
        objPessoaDAO.excluirPessoa(objPessoaDTO);
    }
    
    private void CarregarCampos() {
        int setar = this.tblPessoa.getSelectedRow();
        this.txtIdPessoa.setText(this.tblPessoa.getModel().getValueAt(setar, 0).toString());
        this.txtCpf.setText(this.tblPessoa.getModel().getValueAt(setar, 1).toString());
        this.txtNomePessoa.setText(this.tblPessoa.getModel().getValueAt(setar, 2).toString());
        this.txtDataNascimento.setText(this.tblPessoa.getModel().getValueAt(setar, 3).toString());
        this.txtSexo.setText(this.tblPessoa.getModel().getValueAt(setar, 4).toString());
        this.txtEmail.setText(this.tblPessoa.getModel().getValueAt(setar, 5).toString());
        this.txtTelefone.setText(this.tblPessoa.getModel().getValueAt(setar, 6).toString());
    }
    
    private void LimparCampos() {
        this.txtIdPessoa.setText("");
        this.txtCpf.setText("");
        this.txtNomePessoa.setText("");
        this.txtDataNascimento.setText("");
        this.txtSexo.setText("");
        this.txtEmail.setText("");
        this.txtTelefone.setText("");
        this.txtIdPessoa.requestFocus();
    }

}
