/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VIEW;

import DAO.TurmaDAO;
import DTO.TurmaDTO;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thiago
 */
public class frmTurmaVIEW extends javax.swing.JFrame {

    /** Creates new form frmTurmaTurma */
    public frmTurmaVIEW() {
        initComponents();
        ListarTurma();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdTurma = new javax.swing.JLabel();
        txtIdTurma = new javax.swing.JTextField();
        lblNomeTurma = new javax.swing.JLabel();
        txtNomeTurma = new javax.swing.JTextField();
        lblAnoTurma = new javax.swing.JLabel();
        txtAnoTurma = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurma = new javax.swing.JTable();
        btnCadastrarTurma = new javax.swing.JButton();
        btnAtualizarTurma = new javax.swing.JButton();
        btnDeletarTurma = new javax.swing.JButton();
        btnCarregarDados = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIdTurma.setText("Id Turma");

        txtIdTurma.setEnabled(false);

        lblNomeTurma.setText("Nome");

        lblAnoTurma.setText("Ano");

        tblTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID TURMA", "NOME", "ANO"
            }
        ));
        jScrollPane1.setViewportView(tblTurma);

        btnCadastrarTurma.setText("Cadastrar");
        btnCadastrarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarTurmaActionPerformed(evt);
            }
        });

        btnAtualizarTurma.setText("Atualizar");
        btnAtualizarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTurmaActionPerformed(evt);
            }
        });

        btnDeletarTurma.setText("Deletar");
        btnDeletarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarTurmaActionPerformed(evt);
            }
        });

        btnCarregarDados.setText("Carregar");
        btnCarregarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarDadosActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblIdTurma)
                                .addComponent(txtIdTurma)
                                .addComponent(lblNomeTurma)
                                .addComponent(txtNomeTurma)
                                .addComponent(lblAnoTurma)
                                .addComponent(txtAnoTurma, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrarTurma)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtualizarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeletarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCarregarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAnoTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarTurma)
                    .addComponent(btnAtualizarTurma)
                    .addComponent(btnDeletarTurma)
                    .addComponent(btnCarregarDados))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarTurmaActionPerformed
        CadastrarTurma();
        LimparCampos();
        ListarTurma();
    }//GEN-LAST:event_btnCadastrarTurmaActionPerformed

    private void btnDeletarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarTurmaActionPerformed
        DeletarTurma();
        LimparCampos();
        ListarTurma();
    }//GEN-LAST:event_btnDeletarTurmaActionPerformed

    private void btnAtualizarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTurmaActionPerformed
        AtualizarTurma();
        LimparCampos();
        ListarTurma();
    }//GEN-LAST:event_btnAtualizarTurmaActionPerformed

    private void btnCarregarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarDadosActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btnCarregarDadosActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        frmPrincipalVIEW obj = new frmPrincipalVIEW();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTurmaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTurmaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTurmaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTurmaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTurmaVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarTurma;
    private javax.swing.JButton btnCadastrarTurma;
    private javax.swing.JButton btnCarregarDados;
    private javax.swing.JButton btnDeletarTurma;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnoTurma;
    private javax.swing.JLabel lblIdTurma;
    private javax.swing.JLabel lblNomeTurma;
    private javax.swing.JTable tblTurma;
    private javax.swing.JTextField txtAnoTurma;
    private javax.swing.JTextField txtIdTurma;
    private javax.swing.JTextField txtNomeTurma;
    // End of variables declaration//GEN-END:variables

    private void ListarTurma() {
        try {
            TurmaDAO objTurmaDAO = new TurmaDAO();
            DefaultTableModel model = (DefaultTableModel) this.tblTurma.getModel();
            model.setNumRows(0);
            ArrayList<TurmaDTO> lista = objTurmaDAO.PesquisarTurma();

            for (int num = 0; num < lista.size(); ++num) {
                model.addRow(new Object[]{
                    ((TurmaDTO) lista.get(num)).getId_turma(),
                    ((TurmaDTO) lista.get(num)).getNome_turma(),
                    ((TurmaDTO) lista.get(num)).getAno()
                });
            }
        } catch (Exception var5) {
            JOptionPane.showMessageDialog((Component) null, "Listar Valores VIEW: " + var5);
        }

    }
    
    private void CadastrarTurma() {
        String nome = this.txtNomeTurma.getText();
        int ano = Integer.parseInt(this.txtAnoTurma.getText());
        
        TurmaDTO objTurmaDTO = new TurmaDTO();
        objTurmaDTO.setNome_turma(nome);
        objTurmaDTO.setAno(ano);
        
        TurmaDAO objTurmaDAO = new TurmaDAO();
        objTurmaDAO.cadastrarTurma(objTurmaDTO);
        
    }
    
    private void AtualizarTurma() {
        int id_turma = Integer.parseInt(this.txtIdTurma.getText());
        String nome_turma = this.txtNomeTurma.getText();
        int ano = Integer.parseInt(this.txtAnoTurma.getText());
        
        TurmaDTO objTurmaDTO = new TurmaDTO();
        objTurmaDTO.setId_turma(id_turma);
        objTurmaDTO.setNome_turma(nome_turma);
        objTurmaDTO.setAno(ano);
        
        TurmaDAO objTurmaDAO = new TurmaDAO();
        objTurmaDAO.alterarTurma(objTurmaDTO);
        
    }

    private void DeletarTurma() {
        int id_turma = Integer.parseInt(this.txtIdTurma.getText());
        TurmaDTO objTurmaDTO = new TurmaDTO();
        objTurmaDTO.setId_turma(id_turma);
        TurmaDAO objTurmaDAO = new TurmaDAO();
        objTurmaDAO.excluirTurma(objTurmaDTO);
    }
    
    private void CarregarCampos() {
        int setar = this.tblTurma.getSelectedRow();
        this.txtIdTurma.setText(this.tblTurma.getModel().getValueAt(setar, 0).toString());
        this.txtNomeTurma.setText(this.tblTurma.getModel().getValueAt(setar, 1).toString());
        this.txtAnoTurma.setText(this.tblTurma.getModel().getValueAt(setar, 2).toString());
    }
    
    private void LimparCampos() {
        this.txtIdTurma.setText("");
        this.txtNomeTurma.setText("");
        this.txtAnoTurma.setText("");
        this.txtIdTurma.requestFocus();
    }
}
